Cherrypick callback manager improvement fix.
istio/envoy pull request #263
Opened 2020-09-21 23:38 UTC by incfly

https://github.com/istio/istio/issues/25909
Cherrypick of the original fix as in https://github.com/envoyproxy/envoy/pull/11751.

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-09-21 23:38 UTC, incfly commented
@lambdai @PiotrSikora PTAL, thanks.

2020-09-22 00:35 UTC, istio-testing commented
@incfly: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-release_envoy_release-1.6 | d6c9e8ffbbd9c25af1c81c94ac0d1f797ef951ce | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-release_envoy_release-1.6/34) | `/test test-release_envoy_release-1.6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-22 16:36 UTC, lambdai requested changes
@incfly Thank you!
Since this is cherry-pick, istio/envoy actually missed a few changes which increase the memory usage. The actually usage is fewer than in the original PR. Could you update the PR?

2020-09-22 16:36 UTC, lambdai commented on test/integration/stats_integration_test.cc
> +  EXPECT_MEMORY_EQ(m_per_cluster, 44715);
43765
As per
```
test/integration/stats_integration_test.cc:292: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 43765
  44715
```

2020-09-22 16:36 UTC, lambdai commented on test/integration/stats_integration_test.cc
> +  EXPECT_MEMORY_EQ(m_per_cluster, 36827);
35973 
As per
```
[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithRealSymbolTable/IPv4
test/integration/stats_integration_test.cc:355: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 35973
  36827
Stack trace:
```

2020-09-22 17:15 UTC, incfly commented on test/integration/stats_integration_test.cc
> +  EXPECT_MEMORY_EQ(m_per_cluster, 36827);
Done.

2020-09-22 17:17 UTC, incfly commented on test/integration/stats_integration_test.cc
> +  EXPECT_MEMORY_EQ(m_per_cluster, 44715);
done.

2020-09-22 17:20 UTC, lambdai approved these changes
Awesome!

2020-09-22 17:55 UTC, istio-testing commented
@incfly: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-release_envoy_release-1.6 | d6c9e8ffbbd9c25af1c81c94ac0d1f797ef951ce | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-release_envoy_release-1.6/34) | `/test test-release_envoy_release-1.6`
test-tsan_envoy_release-1.6 | 3f33b4a26f591e3692c671738973967eae3a3d42 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-tsan_envoy_release-1.6/43) | `/test test-tsan_envoy_release-1.6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-22 18:07 UTC, istio-testing commented
@incfly: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-release_envoy_release-1.6 | d6c9e8ffbbd9c25af1c81c94ac0d1f797ef951ce | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-release_envoy_release-1.6/34) | `/test test-release_envoy_release-1.6`
test-tsan_envoy_release-1.6 | 3f33b4a26f591e3692c671738973967eae3a3d42 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-tsan_envoy_release-1.6/43) | `/test test-tsan_envoy_release-1.6`
test-asan_envoy_release-1.6 | 3f33b4a26f591e3692c671738973967eae3a3d42 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-asan_envoy_release-1.6/42) | `/test test-asan_envoy_release-1.6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-22 18:10 UTC, lambdai commented
/retest

2020-09-22 19:00 UTC, istio-testing commented
@incfly: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-asan_envoy_release-1.6 | 3f33b4a26f591e3692c671738973967eae3a3d42 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_envoy/263/test-asan_envoy_release-1.6/43) | `/test test-asan_envoy_release-1.6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-22 19:09 UTC, incfly commented
fails at hot restart at this line.

https://github.com/istio/envoy/blob/3d162074fca24448334e18fb2fa507ffd7819e7e/test/integration/hotrestart_test.sh#L134

```
  check [ "${CLI_HOT_RESTART_VERSION}" = "${EXPECTED_CLI_HOT_RESTART_VERSION}" ]
```

log

```
TEST: Checking for match of --hot-restart-version and admin /hot_restart_version
fetching hot restart version from http://127.0.0.1:38655/hot_restart_version ...
Fetched ADMIN_HOT_RESTART_VERSION is 
     check [  = 11.104 ] ...
```

2020-09-22 19:10 UTC, incfly commented
/retest

2020-09-22 19:58 UTC, merged